### ISSUE TITLE
error when write something

### ISSUE THREAD

**Issue by bekishev04** [serpotapov/stable-diffusion-portable#12]
```
Error verifying pickled file from D:\stable-diffusion\models\Codeformer\codeformer-v0.1.0.pth:
Traceback (most recent call last):
  File "D:\stable-diffusion\modules\safe.py", line 81, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "D:\stable-diffusion\python\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "D:\stable-diffusion\python\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\stable-diffusion\modules\safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "D:\stable-diffusion\modules\safe.py", line 102, in check_pt
    unpickler.load()
_pickle.UnpicklingError: persistent IDs in protocol 0 must be ASCII strings

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.


Error completing request
Arguments: ('task(pwwk3uadfwlatov)', 'girl', 'deformed, bad anatomy, disfigured, poorly drawn face, mutation, mutated, extra limb, ugly, disgusting, poorly drawn hands, missing limb, floating limbs, disconnected limbs, malformed hands, blurry, ((((mutated hands and fingers)))), watermark, watermarked, oversaturated, censored, distorted hands, amputation, missing hands, obese, doubled face, double hands', [], 20, 0, True, False, 1, 1, 8, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "D:\stable-diffusion\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "D:\stable-diffusion\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "D:\stable-diffusion\modules\processing.py", line 661, in process_images_inner
    x_sample = modules.face_restoration.restore_faces(x_sample)
  File "D:\stable-diffusion\modules\face_restoration.py", line 19, in restore_faces
    return face_restorer.restore(np_image)
  File "D:\stable-diffusion\modules\codeformer_model.py", line 88, in restore
    self.create_models()
  File "D:\stable-diffusion\modules\codeformer_model.py", line 65, in create_models
    checkpoint = torch.load(ckpt_path)['params_ema']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Lex-DRL** [comment]
@bekishev04 

This repo is just a web-installer. Literally that, nothing more. It doesn't contain neiter SD nor webui themselves. What it does is:
- it contains bundled python and git
- it sets paths to them via a cmd script for the actual SD to use
- it simply downloads the official SD repo and keeps the modified bat (with paths to python and git set)
- it also includes a config with some pre-defined settings that @XpucT decided should be default _(I personally disagree that it should be included to override AUTOMATIC's defaults, but who am I to judge?)_.

So, unless your issue is related with **initial SD installation itself** (and installation only), all the issues should be redirected to the Automatic's SD repo.

Now, with that said, what I'd suggest you to do is:
1. Ensure you have proper security settings on the folder and all of it's descendents. Basically:
  - right-click on the folder > security tab
  - give full access for all of the listed (it's enough to do it for Administarators, SYSTEM, Users and Authorised Users)
  - Upon clicking on "Advanced", override all of the descendents with these permissions
2. Ensure the path itself doesn't contain any non-ASCII characters **OR** spaces. (RU: по нику я предполагаю, что ты русскоговорящий - так что если это так, убедись, что в пути к папке **ТОЧНО** нет никакой кириллицы; EN: if you don't speak russian, ignore this remark). Preferrably, you should put it into the shortest path possible., like `D:\SD`
3. In Windows, there's a built-in path limit of 256 chars, which is enabled by default. Yeah, stupid windows defaults, once again. When you install Python normally (and not just use the bundled one here), the installer suggests you to remove that restriction via a registry tweak. You can google how to do it yourself.
4. If NOTHING of the above helps, you should really try to re-install SD from scratch.
  - First, create the folder at the right path right away (`D:\SD` / `C:\SD`)
  - **THEN** set permissions of this **EMPTY** folder to full, as I described above
  - **ONLY THEN** put the contents of this repo to it and launch the install script. Launch it regularly, **NOT** as an admin (otherwise all the created files will be owned by administrator and, once again, you might have access issues later).
  - If it goes fine, then you can take the config files / models from your current (broken) install.

**Comment by bekishev04** [comment]
Так давай на русском, в путях русских букв нет. Стоит в корне. Рядом поставил оригинал с https://github.com/AUTOMATIC1111/stable-diffusion-webui работает. И да я запускал все от имени администратора, в том числе установка и запуск.

Можешь подсказать раз все сейчас с оригинальным работает откуда настройки перенести, чтоб по умолчанию были ваши?

**Comment by serpotapov** [comment]
Приветствую 🖐
У Вас недокачался CodeFormer.
1. Закройте Stable Diffusion.
2. Перейдите в папку D:\stable-diffusion\models\Codeformer и удалите там все файлы.
3. Запустите Stable Diffusion и сгенерируйте картинку со включённым Restore face. Подождите, будет загружена модель для Restore face, не дёргайте батник. Да, выглядеть всё будет, как будто зависло. Это нормально. Просто ждите.

**Comment by Lex-DRL** [comment]
@bekishev04 

1. А вот не надо было запускать инсталлер от админа.
2. Прямо сейчас - я не за тем компом, на котором у меня SD. Там в корне лежат 2 json-файла. Чо-то там просто config, и чо-то там ui config. Вот это - префы.
3. Модели, всякие ЛОРы, эмбеддинги, output'ы - в соответствующих папках.

Если у тебя нормально работает оф. инсталл от автоматика - так используй его. Этот репо - БУКВАЛЬНО выкачивает его же. Просто перекинь в его папку всё, что руками доставлял в эту, поломанную.

**Comment by Lex-DRL** [comment]
С портабельными прогами лучше так не делать... и лучше немного вкурить виндовые пермишены к папкам.
ОК, удачи. Я чисто мимо проходил - вот и ответил.
